#!/usr/bin/env bash
#
# Write `pubspec_overrides.yaml` files so the federated CallBundle packages
# resolve against each other from source. This is needed before the packages
# are published (their hosted `^x.y.z` constraints aren't on pub.dev yet) and
# gives CI a deterministic resolution that doesn't depend on melos's
# environment-specific override generation.
#
# `pub get` for a plugin package also resolves that package's `example/` folder,
# so the per-plugin examples are wired up too. The generated files are gitignored
# and are NOT part of any published package archive, so it is safe to run this in
# CI.
#
# Usage: tool/wire_overrides.sh

set -euo pipefail

cd "$(dirname "$0")/.."

# write_overrides <pubspec_overrides_path> <dep1> <path1> [<dep2> <path2> ...]
write_overrides() {
  local file="$1"
  shift
  {
    echo "# Generated by tool/wire_overrides.sh — local path overrides for CI/dev."
    echo "dependency_overrides:"
    while [ "$#" -gt 0 ]; do
      printf '  %s:\n    path: %s\n' "$1" "$2"
      shift 2
    done
  } >"$file"
  echo "wrote $file"
}

# Root-level packages (siblings of each other).
write_overrides callbundle_android/pubspec_overrides.yaml \
  callbundle_platform_interface ../callbundle_platform_interface
write_overrides callbundle_ios/pubspec_overrides.yaml \
  callbundle_platform_interface ../callbundle_platform_interface
write_overrides callbundle/pubspec_overrides.yaml \
  callbundle_platform_interface ../callbundle_platform_interface \
  callbundle_android ../callbundle_android \
  callbundle_ios ../callbundle_ios
write_overrides example/pubspec_overrides.yaml \
  callbundle ../callbundle \
  callbundle_platform_interface ../callbundle_platform_interface \
  callbundle_android ../callbundle_android \
  callbundle_ios ../callbundle_ios

# Per-plugin example apps (resolved transitively by `pub get` on the plugin).
write_overrides callbundle_android/example/pubspec_overrides.yaml \
  callbundle_android .. \
  callbundle_platform_interface ../../callbundle_platform_interface
write_overrides callbundle_ios/example/pubspec_overrides.yaml \
  callbundle_ios .. \
  callbundle_platform_interface ../../callbundle_platform_interface
